version: '3'
services:
  mongodb:
    image: mongo:3.7.9-jessie
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis:4.0-alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: always